INSERT INTO `bookdiarydb`.`genre`
(`genre_name_en`,
`genre_name_ro`,
`genre_name_hu`)
VALUES
("Action-adventure","Acțiune, aventură","Akció-kaland"),
("Anthology","Antologie","Antológia"),
("Classic","Clasic","Klasszikus"),
("Comics, graphic novel","Benzi desenate, roman grafic","Képregény, grafikus regény"),
("Crime, detective","Polițist, crimă","Bűncselekmény, krimi"),
("Drama","Dramă","Dráma"),
("Fable","Fabulă","Mese"),
("Fairy tale","Basm, poveste","Tündérmese"),
("Fan fiction","Fan fiction","Fanfiction"),
("Fantasy","Fantezie","Fantázia"),
("Historical fiction","Ficțiune istorică","Történelmi fikció"),
("Horror","Groază","Rémtörténet"),
("Humor","Umor","Humor"),
("Legend","Legendă","Legenda"),
("Magical realism","Realism magic","Mágikus realizmus"),
("Mystery","Mister","Rejtély"),
("Mythology","Mitologie","Mitológia"),
("Realistic fiction","Ficțiune realistică","Reális fikció"),
("Romance, satire","Romantic, satiră","Romantika, szatíra"),
("Science fiction","Științifico-fantastic","Tudományos-fantasztikus"),
("Short story","Poveste scurtă","Elbeszélés"),
("Suspense, thriller","Suspans, thriller","Izgalmas, thriller"),
("Biography, autobiography","Biografie, autobiografie","Életrajz, önéletrajz"),
("Essay","Eseu","Esszé"),
("Memoir","Memoriu","Emlékirat"),
("Narrative nonfiction","Non-ficțiune narativă","Narratív irodalom"),
("Periodical","Revistă","Folyóírat"),
("Reference book","Carte de referință","Szakkönyv"),
("Self help book","Carte de auto-ajutor","Önsegítő könyv"),
("Speech","Discurs","Beszéd"),
("Textbook","Manual","Tankönyv"),
("Poetry","Poezie","Költészet"),
("Unknown","Necunoscut","Ismeretlen");
